### ISSUE TITLE
Is it possible to automatically detect the cursor?

### ISSUE THREAD

**Issue by Jannchie** [CatsJuice/ipad-cursor#10]
Manually specifying whether the cursor is displayed as text seems a bit tricky. Can we automatically change the cursor by the cursor style of the element the cursor is pointing to?

It would probably be written like this:

``` js
// target is the dom element
const computedStyle = getComputedStyle(target);
const cursor = computedStyle.cursor;
if (cursor === 'text') {
   ...
} 
```

I'm not sure if this will have performance issues...

**Comment by Jannchie** [comment]
Oh, I see that all the cursors have been set to none...

**Comment by CatsJuice** [comment]
Currently, cursor changes are detected by **adding a mouse event to the specified target element** to detect whether the cursor type needs to be changed.

From this point, it's impossible to listen all element, or just listen `mousemove` on window, and check the target.

And then it's hard to judge if target is a `text`:

- judge by cursor in `computedStyle` as you mentioned(not working)
- judge display `inline`(not accurate enough)
- judge content inner element (maybe complex...)

Even if the above is achieved, it may conflict with `block` behavior....

Feel free to suggest new ideas!

**Comment by CatsJuice** [comment]
> Currently, cursor changes are detected by **adding a mouse event to the specified target element** to detect whether the cursor type needs to be changed.
> 
> From this point, it's impossible to listen all element, or just listen `mousemove` on window, and check the target.
> 
> And then it's hard to judge if target is a `text`:
> 
> * judge by cursor in `computedStyle` as you mentioned(not working)
> * judge display `inline`(not accurate enough)
> * judge content inner element (maybe complex...)
> 
> Even if the above is achieved, it may conflict with `block` behavior....
> 
> Feel free to suggest new ideas!

🤔 Maybe  the conflict could be resolved by adding a lock state when `block` is active.
I'll try to implement this, maybe through a optional config like `autoDetectText` to enable this feature, which by default, will  not be enabled.

**Comment by Jannchie** [comment]
I succeeded, I'll create a prototype PR later...
