### ISSUE TITLE
`scale` is not working before cursor enters a block 

### ISSUE THREAD

**Issue by OverflowCat** [CatsJuice/ipad-cursor#15]
```css
  transform:
    translate(calc(-50% + var(--cursor-translateX)), calc(-50% + var(--cursor-translateY)))
    scale(var(--cursor-scale));
```

`--cursor-translateX` and `--cursor-translateX` are first set in `onBlockMove()`, which will only be triggered when mouse is moving on a block. Therefore, these two CSS variables are undefined before the cursor enters a block, resulting in the `transform` property being `none`. Consequently, `scale` will not work.

![image](https://github.com/CatsJuice/ipad-cursor/assets/20166026/b640b54f-1163-4a7e-8b04-48232d1f375f)

**Comment by CatsJuice** [comment]
Thanks, it's fixed and will be released later. Feel free to report issue if still have problems.
