### ISSUE TITLE
Support for Hexo (NexT theme)

### ISSUE THREAD

**Issue by zqqcee** [CatsJuice/ipad-cursor#31]
Thanks for this repo!!
Recently, I wanna add this `ipad-cursor` into my blog built by hexo (NexT theme). But I don't know how to do that :)

**Comment by CatsJuice** [comment]
I'm sorry but I'm not familiar whit `hexo`. 

It's much possible that a plugin of `hexo` is required. I'll keep this issue open, maybe someone could help with it.

**Comment by zqqcee** [comment]
Thank you !
Meanwhile, I'll try my best to figure out the solution

**Comment by zqqcee** [comment]
> I'm sorry but I'm not familiar whit `hexo`.
> 
> It's much possible that a plugin of `hexo` is required. I'll keep this issue open, maybe someone could help with it.

I've made it,  I'll post an article to tell how to do that.

**Comment by zqqcee** [comment]
@CatsJuice 

Hi~!

I've written an article to show how to add `ipad-cursor` into the hexo(theme:NexT) blog [在博客中应用ipad-cursor，@Hexo(Theme:NexT)](https://zqqcee.github.io/2023/07/23/ebae3e5deab8/)

Moreover, I published a package to add `data-cursor` in a configurable and more convenient way, named "ipad-cursor-hexo"
[zqqcee/ipad-cursor-hexo](https://github.com/zqqcee/ipad-cursor-hexo)

(Meanwhile, sorry for that I'm not very much familiar with open source regulation, and I don't know if creating a new repository is appropriate)

**Comment by zqqcee** [comment]
@CatsJuice 

Great thanks for this amazing project！👏

It inspired me a lot!

**Comment by CatsJuice** [comment]
@zqqcee thx a lot, I'll update docs later to introduce how to use with other tools like `Hexo`

**Comment by CatsJuice** [comment]
Added to [README](https://github.com/CatsJuice/ipad-cursor#use-in-framework)
