### ISSUE TITLE
how to disable the default cursor style

### ISSUE THREAD

**Issue by zqqcee** [CatsJuice/ipad-cursor#32]
## Reproduce
I've set the `data-cursor="block"` attribute on both tags
<img width="1172" alt="image" src="https://github.com/CatsJuice/ipad-cursor/assets/55946653/520509fb-3acd-4b6a-9aff-4bd0e6d50818">

https://github.com/CatsJuice/ipad-cursor/assets/55946653/299a5f39-fd2a-4b0b-a428-37e2de78ec77

## Description
Could you please tell me how to achieve this effect? I didn't find the solution in documentation :P

https://github.com/CatsJuice/ipad-cursor/assets/55946653/8642ba6a-c036-416b-873f-9228b50e7676

**Comment by CatsJuice** [comment]
@zqqcee 
- For the first, some element like `button` / `a` has a default behavior that cursor will be `pointer`. I just apply `cursor: none` for `*` selector, but this may be overrode  by others like ui framework, component. I'll consider to add `!important` support, but for now you need to set cursor to `none` for these elements yourself.
- For the second, I'm not sure which part you are interested in.
  - The source code can be find [here](https://github.com/CatsJuice/ipad-cursor/blob/main/playground/src/components/AppHeader.vue)
  - And the `lighting` effect is on (which by default, is off): `enableLighting: true` 
  - For the hovered border, it's the default style that configured in [source code](https://github.com/CatsJuice/ipad-cursor/blob/32f6af20f083f758379c375a723230af0060bcb0/src/index.ts#L234). You can customize your style by passing a config, docs [here](https://github.com/CatsJuice/ipad-cursor/blob/32f6af20f083f758379c375a723230af0060bcb0/src/index.ts#L234)
  - The full config that I use in playground:
      ```ts
        const { updateConfig } = useCursor({
            enableMouseDownEffect: true,
            enableAutoTextCursor: true,
            enableLighting: true,
            normalStyle: {
              scale: 1,
            },
            blockPadding: "auto",
            blockStyle: {
              radius: "auto",
            },
        });
      ```

**Comment by zqqcee** [comment]
> 

Thanks very much!

**Comment by zqqcee** [comment]
@CatsJuice 

I solved this problem by applying `cursor: none` for `* `selector **one more time**.

It's overrode by third-party plugin. 

It would be better to add `!important`  into it , in my opinion :)
